# Generated by Django 3.0.8 on 2020-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmpw',
            field=models.CharField(default='0000', max_length=128, verbose_name='confirm'),
        ),
    ]
