# Generated by Django 3.0.8 on 2020-07-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_confirmpw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='spouse_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='A', max_length=2, verbose_name='usertype'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmpw',
            field=models.CharField(default='0000', max_length=128, verbose_name='confirmpw'),
        ),
    ]
