# Generated by Django 3.0.8 on 2020-08-12 04:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WearerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.datetime(2020, 8, 12, 4, 49, 44, 885686, tzinfo=utc), verbose_name='nowTime')),
                ('tempHumid', models.CharField(max_length=150, verbose_name='temp&humid_sensor')),
                ('atmosPress', models.CharField(max_length=150, verbose_name='atmospherePressure_sensor')),
                ('gyro', models.CharField(max_length=150, verbose_name='gyro_sensor')),
                ('accel', models.CharField(max_length=150, verbose_name='accelerate_sensor')),
                ('heartRate', models.CharField(max_length=150, verbose_name='heartRate_sensor')),
                ('sound', models.CharField(max_length=150, verbose_name='sound_sensor')),
                ('vibrate', models.CharField(max_length=150, verbose_name='vibrate_sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
