# Generated by Django 3.0.8 on 2020-10-23 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WearerLocation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nowDT', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WearerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField(auto_now_add=True, null=True, verbose_name='now date')),
                ('heartRate_max', models.FloatField(verbose_name='day heart rate max')),
                ('heartRate_min', models.FloatField(verbose_name='day heart rate min')),
                ('heartRate_avg', models.FloatField(verbose_name='day heart rate avg')),
                ('temp_max', models.FloatField(verbose_name='temp rate max')),
                ('temp_avg', models.FloatField(verbose_name='temp rate avg')),
                ('temp_min', models.FloatField(verbose_name='temp rate min')),
                ('humid_max', models.FloatField(verbose_name='humid rate max')),
                ('humid_avg', models.FloatField(verbose_name='humid rate avg')),
                ('humid_min', models.FloatField(verbose_name='humid rate min')),
                ('stepCount', models.IntegerField(verbose_name='day step count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WearerMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDT', models.DateTimeField(auto_now=True, verbose_name='now date time')),
                ('meter', models.IntegerField(verbose_name='meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WearerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField(auto_now_add=True, verbose_name='nowTime')),
                ('nowTime', models.TimeField(auto_now_add=True, verbose_name='nowTime')),
                ('fallEvent', models.BooleanField(default=False, null=True)),
                ('heartEvent', models.CharField(default='N', max_length=1, null=True)),
                ('heatIllEvent', models.CharField(default='N', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WearerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField(auto_now_add=True, null=True, verbose_name='nowTime')),
                ('nowTime', models.TimeField(auto_now_add=True, null=True, verbose_name='nowTime')),
                ('temp', models.CharField(default='20', max_length=50, verbose_name='temp_sensor')),
                ('humid', models.CharField(default='50', max_length=50, verbose_name='humid_sensor')),
                ('heartRate', models.CharField(max_length=50, verbose_name='heartRate_sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeatPreEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField(auto_now_add=True)),
                ('nowTime', models.TimeField(auto_now_add=True)),
                ('a_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('b_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('alarmedDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('eventType', models.CharField(default='N', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectHeartEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField(auto_now_add=True)),
                ('nowTime', models.TimeField(auto_now_add=True)),
                ('s_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('b_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('s_alarmedDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('b_alarmedDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('eventType', models.CharField(default='N', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
