# Generated by Django 3.0.8 on 2020-08-12 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 12, 4, 50, 35, 608602, tzinfo=utc), verbose_name='nowTime'),
        ),
    ]
