# Generated by Django 3.0.8 on 2020-08-17 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 17, 13, 31, 19, 800983, tzinfo=utc), verbose_name='nowTime'),
        ),
    ]
