# Generated by Django 3.0.8 on 2020-10-24 20:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 10, 24), null=True, verbose_name='nowDate'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(20, 55, 33, 719455), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearermeter',
            name='nowDT',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='now date time'),
        ),
    ]
