# Generated by Django 3.0.8 on 2020-10-24 21:09

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0002_auto_20201024_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(21, 9, 9, 741777), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='nowDate',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='now date'),
        ),
    ]
