# Generated by Django 3.0.8 on 2020-08-17 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0002_auto_20200817_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 17, 13, 34, 10, 924809, tzinfo=utc), verbose_name='nowTime'),
        ),
    ]
