# Generated by Django 3.0.8 on 2020-08-20 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0003_auto_20200817_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 20, 6, 55, 10, 470751, tzinfo=utc), verbose_name='nowTime'),
        ),
    ]
