# Generated by Django 3.0.8 on 2020-08-20 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0004_auto_20200820_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 20, 7, 1, 59, 33359, tzinfo=utc), verbose_name='nowTime'),
        ),
    ]
