# Generated by Django 3.0.8 on 2020-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0005_auto_20200820_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wearerdata',
            name='atmosPress',
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='accel',
            field=models.CharField(max_length=50, verbose_name='accelerate_sensor'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='gyro',
            field=models.CharField(max_length=50, verbose_name='gyro_sensor'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='heartRate',
            field=models.CharField(max_length=50, verbose_name='heartRate_sensor'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='sound',
            field=models.CharField(max_length=50, verbose_name='sound_sensor'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='tempHumid',
            field=models.CharField(max_length=50, verbose_name='temp&humid_sensor'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='vibrate',
            field=models.CharField(max_length=50, verbose_name='vibrate_sensor'),
        ),
    ]
