# Generated by Django 3.0.8 on 2020-08-12 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0005_auto_20200812_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 12, 12, 26, 43, 992693, tzinfo=utc), verbose_name='nowTime'),
        ),
    ]
