# Generated by Django 3.0.8 on 2020-08-12 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0006_auto_20200812_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 12, 13, 21, 20, 666729, tzinfo=utc), verbose_name='nowTime'),
        ),
    ]
