# Generated by Django 3.0.8 on 2020-09-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0007_auto_20200901_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='stepCount',
            field=models.CharField(default='200', max_length=50, verbose_name='stepCount'),
        ),
    ]
