# Generated by Django 3.0.8 on 2020-09-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0008_auto_20200901_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wearerdata',
            old_name='time',
            new_name='nowTime',
        ),
    ]
