# Generated by Django 3.0.8 on 2020-09-01 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0009_auto_20200901_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 15, 18, 45, 61410), null=True, verbose_name='nowTime'),
        ),
    ]
