# Generated by Django 3.0.8 on 2020-09-01 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0010_auto_20200901_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wearerdata',
            name='tempHumid',
        ),
        migrations.AddField(
            model_name='wearerdata',
            name='humid',
            field=models.CharField(default='50', max_length=50, verbose_name='humid_sensor'),
        ),
        migrations.AddField(
            model_name='wearerdata',
            name='temp',
            field=models.CharField(default='20', max_length=50, verbose_name='temp_sensor'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 21, 39, 56, 303545), null=True, verbose_name='nowTime'),
        ),
    ]
