# Generated by Django 3.0.8 on 2020-09-02 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0011_auto_20200901_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearerdata',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 2), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(17, 45, 44, 447292), null=True, verbose_name='nowTime'),
        ),
    ]
