# Generated by Django 3.0.8 on 2020-09-03 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0012_auto_20200902_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 3), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(17, 43, 33, 206054), null=True, verbose_name='nowTime'),
        ),
    ]
