# Generated by Django 3.0.8 on 2020-09-03 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0013_auto_20200903_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(21, 51, 7, 700599), null=True, verbose_name='nowTime'),
        ),
    ]
