# Generated by Django 3.0.8 on 2020-09-03 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0015_auto_20200903_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 13, 59, 156786), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 13, 59, 157311), null=True, verbose_name='nowTime'),
        ),
    ]
