# Generated by Django 3.0.8 on 2020-09-06 12:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wearerData', '0016_auto_20200903_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 6), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(12, 49, 49, 780919), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 6), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(12, 49, 49, 781472), null=True, verbose_name='nowTime'),
        ),
        migrations.CreateModel(
            name='WearerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField(default=datetime.date(2020, 9, 6), null=True, verbose_name='now date')),
                ('heartRate_max', models.IntegerField(verbose_name='day heart rate max')),
                ('heartRate_min', models.IntegerField(verbose_name='day heart rate min')),
                ('heartRate_avg', models.IntegerField(verbose_name='day heart rate avg')),
                ('sound_max', models.IntegerField(verbose_name='day sound max')),
                ('sound_avg', models.IntegerField(verbose_name='day sound avg')),
                ('sound_min', models.IntegerField(verbose_name='day sound min')),
                ('temp_max', models.IntegerField(verbose_name='temp rate max')),
                ('temp_avg', models.IntegerField(verbose_name='temp rate avg')),
                ('temp_min', models.IntegerField(verbose_name='temp rate min')),
                ('humid_max', models.IntegerField(verbose_name='humid rate max')),
                ('humid_avg', models.IntegerField(verbose_name='humid rate avg')),
                ('humid_min', models.IntegerField(verbose_name='humid rate min')),
                ('stepCount', models.IntegerField(verbose_name='day step count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
