# Generated by Django 3.0.8 on 2020-09-06 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0017_auto_20200906_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(13, 50, 51, 699107), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(13, 50, 51, 699647), null=True, verbose_name='nowTime'),
        ),
    ]
