# Generated by Django 3.0.8 on 2020-09-06 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0018_auto_20200906_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(15, 42, 5, 203254), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(15, 42, 5, 203809), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='heartRate_avg',
            field=models.FloatField(verbose_name='day heart rate avg'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='humid_avg',
            field=models.FloatField(verbose_name='humid rate avg'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='sound_avg',
            field=models.FloatField(verbose_name='day sound avg'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='temp_avg',
            field=models.FloatField(verbose_name='temp rate avg'),
        ),
    ]
