# Generated by Django 3.0.8 on 2020-09-11 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0019_auto_20200906_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 11), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(21, 29, 47, 672433), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 11), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(21, 29, 47, 673170), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 11), null=True, verbose_name='now date'),
        ),
    ]
