# Generated by Django 3.0.8 on 2020-09-12 22:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wearerData', '0021_auto_20200911_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatPreEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField(default=datetime.date(2020, 9, 12), null=True)),
                ('a_start', models.TimeField(default=datetime.time(22, 51, 33, 876391), null=True)),
                ('b_start', models.TimeField(default=datetime.time(22, 51, 33, 876402), null=True)),
                ('c_start', models.TimeField(default=datetime.time(22, 51, 33, 876412), null=True)),
                ('eventType', models.CharField(default='N', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wearerevent',
            name='heatIllEvent',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 12), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(22, 51, 33, 875892), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 12), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(22, 51, 33, 876783), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 12), null=True, verbose_name='now date'),
        ),
        migrations.DeleteModel(
            name='WearerPreEvent',
        ),
    ]
