# Generated by Django 3.0.8 on 2020-09-25 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0022_auto_20200912_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatpreevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(21, 59, 43, 507839), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='a_start',
            field=models.TimeField(default=datetime.time(21, 59, 43, 507851), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='b_start',
            field=models.TimeField(default=datetime.time(21, 59, 43, 507860), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='c_start',
            field=models.TimeField(default=datetime.time(21, 59, 43, 507871), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 25), null=True),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 25), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(21, 59, 43, 507344), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 25), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(21, 59, 43, 508239), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='nowDate',
            field=models.DateField(default=datetime.date(2020, 9, 25), null=True, verbose_name='now date'),
        ),
    ]
