# Generated by Django 3.0.8 on 2020-09-25 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0023_auto_20200925_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatpreevent',
            name='a_start',
            field=models.TimeField(default=datetime.time(23, 45, 38, 714375), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='b_start',
            field=models.TimeField(default=datetime.time(23, 45, 38, 714385), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='c_start',
            field=models.TimeField(default=datetime.time(23, 45, 38, 714397), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 45, 38, 714363), null=True),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 45, 38, 713833), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 45, 38, 714764), null=True, verbose_name='nowTime'),
        ),
    ]
