# Generated by Django 3.0.8 on 2020-09-25 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0024_auto_20200925_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatpreevent',
            name='a_start',
            field=models.TimeField(default=datetime.time(23, 46, 54, 73558), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='b_start',
            field=models.TimeField(default=datetime.time(23, 46, 54, 73567), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='c_start',
            field=models.TimeField(default=datetime.time(23, 46, 54, 73578), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 46, 54, 73547), null=True),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 46, 54, 73038), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 46, 54, 73948), null=True, verbose_name='nowTime'),
        ),
    ]
