# Generated by Django 3.0.8 on 2020-09-25 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0025_auto_20200925_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatpreevent',
            name='a_start',
            field=models.TimeField(default=datetime.time(23, 50, 9, 81544), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='b_start',
            field=models.TimeField(default=datetime.time(23, 50, 9, 81554), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='c_start',
            field=models.TimeField(default=datetime.time(23, 50, 9, 81564), null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 50, 9, 81532), null=True),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 50, 9, 80964), null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=datetime.time(23, 50, 9, 81932), null=True, verbose_name='nowTime'),
        ),
    ]
