# Generated by Django 3.0.8 on 2020-09-25 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0026_auto_20200925_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatpreevent',
            name='a_start',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='b_start',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='c_start',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='nowDate',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='nowTime',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowDate',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerdata',
            name='nowTime',
            field=models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowDate',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='nowDate',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='now date'),
        ),
    ]
