# Generated by Django 3.0.8 on 2020-09-26 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0028_auto_20200926_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatpreevent',
            name='a_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='b_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='c_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='nowDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='heatpreevent',
            name='nowTime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowDate',
            field=models.DateField(auto_now_add=True, verbose_name='nowTime'),
        ),
        migrations.AlterField(
            model_name='wearerevent',
            name='nowTime',
            field=models.TimeField(auto_now_add=True, verbose_name='nowTime'),
        ),
    ]
