# Generated by Django 3.0.8 on 2020-09-26 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0029_auto_20200926_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatpreevent',
            name='alarmedDT',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
