# Generated by Django 3.0.8 on 2020-09-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0030_heatpreevent_alarmeddt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerstats',
            name='heartRate_max',
            field=models.FloatField(verbose_name='day heart rate max'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='heartRate_min',
            field=models.FloatField(verbose_name='day heart rate min'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='humid_max',
            field=models.FloatField(verbose_name='humid rate max'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='humid_min',
            field=models.FloatField(verbose_name='humid rate min'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='sound_max',
            field=models.FloatField(verbose_name='day sound max'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='sound_min',
            field=models.FloatField(verbose_name='day sound min'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='temp_max',
            field=models.FloatField(verbose_name='temp rate max'),
        ),
        migrations.AlterField(
            model_name='wearerstats',
            name='temp_min',
            field=models.FloatField(verbose_name='temp rate min'),
        ),
    ]
