# Generated by Django 3.0.8 on 2020-09-26 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20200926_1902'),
        ('wearerData', '0031_auto_20200926_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='WearerLocation',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nowDT', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
    ]
