# Generated by Django 3.0.8 on 2020-09-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0033_auto_20200928_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wearermeter',
            name='nowDate',
        ),
        migrations.AddField(
            model_name='wearermeter',
            name='nowDT',
            field=models.DateTimeField(auto_now=True, verbose_name='now date time'),
        ),
        migrations.AlterField(
            model_name='wearermeter',
            name='meter',
            field=models.IntegerField(verbose_name='meter'),
        ),
    ]
