# Generated by Django 3.0.8 on 2020-09-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wearerData', '0034_auto_20200928_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearermeter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
