# Generated by Django 3.0.8 on 2020-09-28 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0035_auto_20200928_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerdata',
            name='stepCount',
            field=models.CharField(default='0', max_length=50, verbose_name='stepCount'),
        ),
        migrations.AlterField(
            model_name='wearermeter',
            name='nowDT',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='now date time'),
        ),
    ]
