# Generated by Django 3.0.8 on 2020-09-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0036_auto_20200928_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearermeter',
            name='nowDT',
            field=models.DateTimeField(auto_now=True, verbose_name='now date time'),
        ),
    ]
