# Generated by Django 3.0.8 on 2020-09-28 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0037_auto_20200928_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerstats',
            name='nowDate',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='now date'),
        ),
    ]
