# Generated by Django 3.0.8 on 2020-09-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0038_auto_20200928_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerstats',
            name='nowDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='now date'),
        ),
    ]
