# Generated by Django 3.0.8 on 2020-09-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0039_auto_20200928_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wearerdata',
            name='stepCount',
        ),
    ]
