# Generated by Django 3.0.8 on 2020-10-21 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wearerData', '0040_remove_wearerdata_stepcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wearerdata',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='wearerstats',
            name='sound_avg',
        ),
        migrations.RemoveField(
            model_name='wearerstats',
            name='sound_max',
        ),
        migrations.RemoveField(
            model_name='wearerstats',
            name='sound_min',
        ),
        migrations.CreateModel(
            name='DetectHeartEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowDate', models.DateField(auto_now_add=True)),
                ('nowTime', models.TimeField(auto_now_add=True)),
                ('s_start', models.BooleanField(default=django.utils.timezone.now)),
                ('b_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('s_alarmedDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('b_alarmedDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('eventType', models.CharField(default='N', max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
