# Generated by Django 3.0.8 on 2020-10-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearerData', '0041_auto_20201021_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearerevent',
            name='heartEvent',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
    ]
